{% set version = '1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-biwt
  version: {{ version|replace("-", "_") }}

source:
  fn: biwt_1.0.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/biwt_1.0.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/biwt/biwt_1.0.tar.gz
  sha256: 2428758fad46b1569b58e4985806c0df79e9fd3a3115d4902512f5e127ea63d5

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-mass
    - r-rrcov

  run:
    - r-base
    - r-mass
    - r-rrcov

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('biwt')"           # [not win]
    - "\"%R%\" -e \"library('biwt')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=biwt
  license: GPL-2
  summary: Compute multivariate location, scale, and correlation estimates based on Tukey's biweight
    M-estimator.
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: biwt
# Type: Package
# Title: Functions to compute the biweight mean vector and covariance & correlation matrices
# Version: 1.0
# Date: 2009-08-11
# Author: Jo Hardin <jo.hardin@pomona.edu>
# Maintainer: Jo Hardin <jo.hardin@pomona.edu>
# Depends: R (>= 2.1.0), rrcov, MASS
# Description: Compute multivariate location, scale, and correlation estimates based on Tukey's biweight M-estimator.
# License: GPL-2
# LazyLoad: yes
# Packaged: 2012-10-29 08:58:19 UTC; ripley
# Repository: CRAN
# Date/Publication: 2012-10-29 08:58:19
# NeedsCompilation: no

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
